name: Project Board

on:
  issues:
    types: [opened, reopened, edited, labeled]
  pull_request:
    types: [opened, reopened, synchronize, labeled]

jobs:
  add-to-project:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Add to GitHub Project
        uses: actions/add-to-project@244f685bbc3b7adfa8466e08b698b5577571133e
        with:
          project-url: ${{ secrets.PROJECT_URL }}
          github-token: ${{ secrets.PROJECTS_TOKEN }}
