name: Project Board

on:
  issues:
    types: [opened, reopened, edited, labeled]
  pull_request:
    types: [opened, reopened, synchronize, labeled]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add to GitHub Project
        uses: actions/add-to-project@v0.6.0
        with:
          project-url: ${{ secrets.PROJECT_URL }}
          github-token: ${{ secrets.PROJECTS_TOKEN }}
